### ISSUE TITLE
principal_components() and rotation

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#67] opened 2019-07-01 10:46 UTC
Is a rotation implemented, or will we have such an option (as currently in `performance::principal_components()`?

**Comment by DominiqueMakowski** [comment] 2019-07-01 10:53
well, technically from what I understood a pca with a rotation is not really a pca anymore, 

hence my approach to this was to actually provide a wrapper for the "true" pca (non rotated) and, at the same time, provide full support for (and encourage people to use) specialized packages for fancier pca/fa, such as the psych pkg 

anyway the sjstats rotated pca relied on psych if I remember correctly, so we might as well simplify it and guide the users to directly use psych (+ easystats)

what do you say?

**Comment by strengejacke** [comment] 2019-07-01 11:27
I would add a `rotation`-option and maybe default it to `NULL`  or so (no rotation). I think that many users use a pca for dimension reduction, and thus want a rotation for the ease of interpreration. And often, when you read "factor analysis", people actually performed a pca (with rotation).

I think it's okay to do a rotation on a PCA (https://stats.stackexchange.com/questions/151653/what-is-the-intuitive-reason-behind-doing-rotations-in-factor-analysis-pca-how). While I agree that PCA and EFA are something completely different (same for FA and EFA), PCA and FA are fairly similar (https://stats.stackexchange.com/a/123136/54740).

I would say a PCA function w/o option for rotation is useless for many (at least in social science) users. I think the advantage of also having a "rotated solution" of the PCA is that we have nice(r) print-methods etc., and everything out-of-the box :-)

**Comment by humanfactors** [comment] 2019-07-02 15:28
Yes, typically rotation is more commonly used in factor analysis than in PCA. However, given the scope of _easy_stats, and the fact that in practice most people would desire the structure of the component loading matrix to approximate a simple structure for exploratory analysis, I think we should default to `NULL` and allow PCA function with rotations.

I can confirm that Varimax Rotated PCA is commonly applied in my field. Of course, ["we should be aware, that "varimax-rotated principal components" are not principal components anymore"](https://stats.stackexchange.com/questions/612/is-pca-followed-by-a-rotation-such-as-varimax-still-pca), and perhaps provide a warning (if someone feels strongly about this 👀). However, I think it should be included if it's a trivial feature.

I don't see any need _not_ to have it on statistical practice or ideological grounds.

**Comment by DominiqueMakowski** [comment] 2019-07-02 15:46
You guys are probably right. In fact, I had no particularly strong reasons not to include rotation (well truth is yes my main argument was that the main name of the function is `principal_components` suggesting the pure extraction of "true" PCs rather than using it for a PC *analysis* (in which one can be more flexible), but the function is currently aliased `PCA` so I guess it's okay :) 

My main rationale was purely practical, since sjstats' implementation of the rotated PCA relied on `psych`, and since `model_parameters` now supports psych anyway (it transforms it so it returns the same object that `principal_components`), we might as well redirect users to use psych's full power for PCA and FA, as such analysis has additional important arguments and parameters (which begs the question, why only allow users to change rotation and not other important arguments? And if we do, why not simply copy psych's function ^^)

**Comment by strengejacke** [comment] 2019-08-05 11:50
This issue looks unsolved to me. ;-)
Do you have any concerns about including a `rotation`-argument? We have the function in *performance* now, which does both (i.e. return rotated and unrotated solutions), and thus we mask function names of our own packages.

**Comment by DominiqueMakowski** [comment] 2019-08-05 12:27
Yes, the rotation arg should be enabled so it can be transferred from performance ☺️ I'll try looking at it asap, but if someone wants to give it a go (copying and readapting the code from performance) please feel free to try

**Comment by strengejacke** [comment] 2019-08-05 13:08
I looked at the code in parameters, but I'm not sure what you're doing there.

``` r
library(parameters)

principal_components(mtcars[, 1:7], n = "all")
#> The 7 principal components accounted for 100.00% of the total variance of the original data (PC1 = 72.66%, PC2 = 16.52%, PC3 = 4.93%, PC4 = 2.26%, PC5 = 1.85%, PC6 = 1.08%, PC7 = 0.70%).
#> 
#> Variable |   PC1 |   PC2 |   PC3 |   PC4 |   PC5 |   PC6 |   PC7 | Complexity
#> -----------------------------------------------------------------------------
#> mpg      | -0.93 |  0.09 | -0.14 | -0.30 |  0.08 |  0.02 |  0.08 |       1.32
#> cyl      |  0.96 |  0.08 | -0.11 | -0.08 | -0.09 | -0.21 |  0.06 |       1.18
#> disp     |  0.95 | -0.09 |  0.07 | -0.23 | -0.05 |  0.04 | -0.14 |       1.21
#> hp       |  0.87 |  0.36 |  0.12 |  0.00 |  0.30 | -0.01 |  0.01 |       1.64
#> drat     | -0.75 |  0.48 |  0.44 | -0.05 | -0.08 | -0.06 | -0.01 |       2.47
#> wt       |  0.88 | -0.35 |  0.26 | -0.04 | -0.06 |  0.10 |  0.14 |       1.60
#> qsec     | -0.54 | -0.81 |  0.17 | -0.02 |  0.12 | -0.11 | -0.03 |       1.97

prcomp(mtcars[, 1:7], retx = TRUE, center = TRUE, scale. = TRUE)
#> Standard deviations (1, .., p=7):
#> [1] 2.2552383 1.0754374 0.5872406 0.3974086 0.3598528 0.2754216 0.2218071
#> 
#> Rotation (n x k) = (7 x 7):
#>             PC1         PC2        PC3          PC4        PC5         PC6
#> mpg  -0.4127573  0.08296098 -0.2416477 -0.766798834  0.2127946  0.09002238
#> cyl   0.4247315  0.07844163 -0.1880252 -0.193926827 -0.2383825 -0.78055217
#> disp  0.4225036 -0.08239922  0.1180359 -0.587679498 -0.1488730  0.16169873
#> hp    0.3877611  0.33696384  0.2027400  0.006884691  0.8314576 -0.04607937
#> drat -0.3311703  0.44858845  0.7552915 -0.117073263 -0.2217502 -0.23319304
#> wt    0.3913153 -0.32236122  0.4405532 -0.107346915 -0.1666473  0.36612190
#> qsec -0.2399275 -0.74932087  0.2943885 -0.061382684  0.3278152 -0.40735764
#>              PC7
#> mpg   0.35069828
#> cyl   0.27276548
#> disp -0.63803744
#> hp    0.03873894
#> drat -0.03702814
#> wt    0.61280387
#> qsec -0.13083413
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment] 2019-08-05 13:10
interesting...

**Comment by DominiqueMakowski** [comment] 2019-08-06 06:56
```
> psych::pca(x, nfactors = 7, rotate = "none")
Principal Components Analysis
Call: principal(r = r, nfactors = nfactors, residuals = residuals, 
    rotate = rotate, n.obs = n.obs, covar = covar, scores = scores, 
    missing = missing, impute = impute, oblique.scores = oblique.scores, 
    method = method)
Standardized loadings (pattern matrix) based upon correlation matrix
       PC1   PC2   PC3  PC4   PC5   PC6   PC7 h2      u2 com
mpg  -0.93 -0.09 -0.14 0.30  0.08 -0.02  0.08  1 2.2e-16 1.3
cyl   0.96 -0.08 -0.11 0.08 -0.09  0.21  0.06  1 3.0e-15 1.2
disp  0.95  0.09  0.07 0.23 -0.05 -0.04 -0.14  1 1.7e-15 1.2
hp    0.87 -0.36  0.12 0.00  0.30  0.01  0.01  1 1.7e-15 1.6
drat -0.75 -0.48  0.44 0.05 -0.08  0.06 -0.01  1 4.4e-16 2.5
wt    0.88  0.35  0.26 0.04 -0.06 -0.10  0.14  1 1.6e-15 1.6
qsec -0.54  0.81  0.17 0.02  0.12  0.11 -0.03  1 1.6e-15 2.
```

psych's results are identical to the current implementation of parameters

Bssically it all boils down to this line:

```
loadings <- as.data.frame(model$rotation %*% diag(model$sdev))
```

`model$rotation` where are the raw loadings displayed in prcomp

**Comment by DominiqueMakowski** [comment] 2019-08-06 06:59
This line was actually copied from the implementation in `performance`, which comes from sjstats 😁

**Comment by DominiqueMakowski** [comment] 2019-08-06 08:04
I streamlined and added the rotation option 😉, will merge the PR once it's green

**Closed** 2019-08-06 08:43 UTC

**Comment by strengejacke** [comment] 2019-08-06 08:57
> This line was actually copied from the implementation in performance, which comes from sjstats 😁

Got it! The unrotated solution is returned by default, while imn _performance_, `principal_components()` returned the explained variance etc. when `rotation = NULL`, and I get the same result when `rotation = "none"`.
