### ISSUE TITLE
Move standardization back to parameters?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#142] opened 2019-10-19 02:56 UTC
My feeling is that standardization is more a part of the parameters package than effectsize. _effectsize_ comprises all the anova-effect-size and effect-size-conversion stuff, which is not needed for model parameters. however, standardization can be useful for both packages, so it should live in the "more basic" package. If standardization is in parameters, it can be used by parameters _and_ effectsize. Else, it can only be used in effectsize. Don't you think so, too?

_Originally posted by @strengejacke in https://github.com/easystats/parameters/pull/139#issuecomment-543891045_

------

I agree that standardization is useful beyond effect sizes related to things. That being said:

- consistency: all the `standardize` and `standardize_` functions are in effectsize, which makes it easy to document, advertise, etc. Rather than having standardize in parameters and `standardize_*` there.
- No cons? Besides an (easy-to-fix) breaking change for users, effectsize is a "free" dependency, meaning that it doesn't increase the dependency weight (since it has virtually none but easystats)

Then you might want to add back standardized parameters `standardize_parameters` and for instance `standardize_priors` back in parameters. But I'd vote against it, because it is quite a sensitive topic and the goal of standardized parameters is usually to obtain some sort of indices of effectsize. Sensitive topic because we are providing some new/improved methods, in need of a visible explanation and documentation, which is more easily done here IMO. "it removes the ability of parameters to give std. coefs" yeah, in the same way that we removed the parameters' possibility to, alone, give effect sizes for ANOVAs etc. 

I feel like the scope is better defined if parameters become strictly about providing a unified interface to parameters' tables (and providing the infrastructure for it, i.e. printing methods, dealing with names etc). Performance does the same for performance indices, and here in effectsize we are able to compute "additional" indices related to the formers. 

I think that moving onwards, once everything is settled, end-uers will prefer using `report(model) %>% to_table()` , which will provide all three of the above in one glance. And for developers/users with specific needs, they can use the lower-level functions (parameters::parameters(), performance::performance() and effectsize functions) which role is more focused and clear. In general, having the three aspects dissociated will make it easier for users to use and for developers to iterate on.

...and parameters still provides a lot of important additional features (with room for improvements), such as parameters_selection, parameters_reduction etc.

**Comment by strengejacke** [comment] 2019-10-19 07:52
I _think_ that we can also have some cyclic dependency, I use the same in sjPlot, where sjmisc is a dependency, but sjmisc _suggests_ sjPlot and uses functions if available. Maybe we can do the same here, too, so standardize can go into effectsize (though my habit/feeling is still that standardization is "importan" and belongs to parameter-stuff, while computing and converting effect sizes and anova stuff is something... "useless" :-D and can be outsourced - but that's more a personal habit as I don't see any reason to use anova instead of (mixed) regression, and converting effect sizes is really "scary", when you think more closely than you want to translate an OR into a d or whatever...).

**Comment by strengejacke** [comment] 2019-10-19 07:54
> I think that moving onwards, once everything is settled, end-uers will prefer using report(model) %>% to_table() , which will provide all three of the above in one glance. 

I'm looking at this from a developers perspective. I use parameters as a broom-alternative in sjPlot, and can easily extract all model parameters (including standardized coefficients), which I then use for the tables.

**Comment by strengejacke** [comment] 2019-10-19 07:56
> in the same way that we removed the parameters' possibility to, alone, give effect sizes for ANOVAs etc.

ANOVAs can be removed completely from methods, so... ;-)

**Comment by mattansb** [comment] 2019-10-19 08:02
I think *standardization* itself, does not belong in either of the packages. So the question is (imo) where is it most useful? Or where does it not make sense for it to *not* be?
The unfortunate thing is that standardized parameters are also a type of effect size.
IMO It is harder to argue for `effectsize` to not have standardized parameter than it is to argue `parameters` not to have this option. (e.g., R<sup>2</sup> is also an effect size! But it wouldn't make sense not to have it in `performance`...)

The best solution then would be to have `effectsize` dependent on `paramters` but maybe `parameters` suggest `effectsize` (I see @strengejacke just suggested this as I was typing 😅). This way if in `model_parameters` someone sets `standardize` they would get maybe a warning if `effectsize` isn't present.

---

As for report, @DominiqueMakowski your comment ^ made we think that perhaps we should focus on the `as_table` methods in an initial release (whenever that is 😋) as have `as_text` come later on (as "what should be in the test, and how" is like... super hard).

---

> ANOVAs can be removed completely from methods, so... ;-)

Would you be more on-board if they were called "LMM effect sizes?" 😉
But I agree that ANOVA effect sizes should only be in `effectsize`.

**Comment by DominiqueMakowski** [comment] 2019-10-19 08:04
>  I use parameters as a broom-alternative in sjPlot, and can easily extract all model parameters (including standardized coefficients), which I then use for the tables.

But it's fairly easy to literally just add `params$Std_Coef <- effectsize::standardize_parameters(model)$Std_Coef`

I mean for me too it's quite a change in habits I must refactor some of my own code too etc., but when I think about documentation etc. I feel like it standardized params migth be better located in a dedidacted repo along with details about how standardization works (also, as a concept) and how is it similar/different from other effect sizes.

But in the end, it doesn't really matter where the functions are located (for the end users) because hopefully people will get used to loading `library(easystats)` and not caring about what is where.

**Comment by DominiqueMakowski** [comment] 2019-10-19 08:06
> The best solution then would be to have effectsize dependent on paramters

This is true! And was originally the plan! Unfortunately, effectsize needs some functions from parameters (e.g. `parameters_table()` and all the `.extract_*` internals), hence the only option was to make it an offpsring of parameters. I think that indeed the import/suggest mild cyclic system would work, same as bayestestR depends on insight but insight suggests bayestestR

**Comment by DominiqueMakowski** [comment] 2019-10-19 08:10
> As for report, @DominiqueMakowski your comment ^ made we think that perhaps we should focus on the as_table methods in an initial release (whenever that is 😋) as have as_text come later on (as "what should be in the test, and how" is like... super hard).

Agreed yeah, this "combine_tables" will surely be the priority for release (but it should not, hopefully, be super complicated). Also I am saying this because based on different feedback, it would be interesting to extend report in the future in its ability to nicely report stuff outside of the console, including compatibility with rmarkdown for the tables (something I think @humanfactors mentioned a while ago), in which case it would be good for it to basically outsource all of the "dirty work" (the generation of the data to report per se)

**Comment by strengejacke** [comment] 2019-10-19 08:24
> But it's fairly easy to literally just add params$Std_Coef <- effectsize::standardize_parameters(model)$Std_Coef

True, but I considered the print() output from model_parameters as a comprehensive summary, and for users it would be nice to have standardized coefficients as well...

> e.g., R2 is also an effect size!

Yes, but it's related to a model, not to a parameters. I see "effectsizes" as something related to single parameters. So, in this sense, yes, standardized coefficients are more related to effectsizes. But in non-psychology fields, coefficients/standardized coefficients are closer than standardized coefficients and eta^2 or such. But that's more a personal habit due to "socialization", so I think it's ok to have it in effectsize. It's just that "standardization" is something I do _before_ I fit models, while all the other things in effectsize are some weird transformations _after_ the model was fitted, that's why I see standardization as a tool rather (completely) unrelated to effectsizes, but typically related to model-fitting. It's more a data transformation than an effectsize per se (same like normalization).

So:

1) we can close this issue
2) standardize goes into effectsize
3) parameters suggest effectsize
4) if effectsize available, model_parameters() can also return standardized coefficients (but that would require some revisions in your dev-branch, to add back the "standardize"-argument?)

**Comment by DominiqueMakowski** [comment] 2019-10-19 08:33
Agreed with 1, 2 and 3. For 4, possible *but* seems fairly useless in the long-term picture once `report` will be able to return this comprehensive dataframe of everything.

**Comment by strengejacke** [comment] 2019-10-19 09:06
I would add a robust option to model_parameters anyway, and I think it's ok and useful to have 4) as well, even if redundant to a possible future feature of report.

**Comment by mattansb** [comment] 2019-10-19 09:09
I also think we should do 4 for completion and convince sake (also to
prevent code brakes, please).

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment] 2019-10-19 09:11
Yes, it is better to be redundant and helpful...

**Comment by DominiqueMakowski** [comment] 2019-10-19 09:11
Right :)

**Comment by DominiqueMakowski** [comment] 2019-10-19 09:41
Now that I think of it, it would definitely make sense for a `standardize = TRUE` arg in model_parameters to return (only) standardized parameters (however, a complete version, including standardized CI, SE, and whatnot), similar to setting a future `robust = TRUE`.

 I.e., arguments in `model_parameters` would change the parameters returned, rather than adding *additional* columns

**Comment by strengejacke** [comment] 2019-10-19 09:42
> I.e., arguments in model_parameters would change the parameters returned, rather than adding additional columns

Yes! Else, it clutters up the output.

**Comment by strengejacke** [comment] 2019-10-19 09:58
maybe we can make it similar to `describe_posterior()`, where we have an argument for multiple options?

Like `arg = c("standardized", "robust", "all")` or similar? Does that make sense?

**Comment by DominiqueMakowski** [comment] 2019-10-19 10:09
Well if we have it in model_parameters, no need to have in describe_posterior (as model_parameters also summarises posteriors)

**Comment by strengejacke** [comment] 2019-10-19 10:12
No, I mean we can use a similar style in model_parameters, where users can decide whether to return only coefficients, only robust, only standardized, a combination of those or all columns.

**Comment by strengejacke** [comment] 2019-10-19 10:14
In either case, the next update of parameters still needs to have the standardize feature implemented, as it else would break code in sjPlot. And if I understand, we need to submit parameters _before_ effectsize? But we don't need the effectsize stuff in parameters for the very next CRAN submission, afaik no other package relies on that.

**Comment by DominiqueMakowski** [comment] 2019-10-19 10:20
> In either case, the next update of parameters still needs to have the standardize feature implemented, as it else would break code in sjPlot

I hope we can potentially release effectsize parameters, some tests just need to be deactivated but it should be okay. This way, you could update SjPot to recover the Std column from effectsize before we release the breaking version of parameters?

**Comment by mattansb** [comment] 2019-10-19 10:23
Does this mean the next release of parameters won't have the effectsize suggest / standardized parameters option?

**Comment by strengejacke** [comment] 2019-10-19 10:24
> Does this mean the next release of parameters won't have the effectsize suggest / standardized parameters option?

It will, if effectsize is released _before_ parameters (and Dominique said this is possible).

So:
effectsize -> sjPlot -> parameters

**Comment by DominiqueMakowski** [comment] 2019-10-19 10:28
Dominique said this *might be* possible :) We'll try once bayestestR is up

**Closed** 2019-10-19 10:49 UTC
