### ISSUE TITLE
model_parameters not working with lme4

### ISSUE THREAD

**Issue by jasonmoy28** [easystats/parameters#585] opened 2021-08-24 12:40 UTC
# Replication: 
`fit = lme4::lmer(data = lme4::cake, formula = 'angle ~ temperature + (temperature|recipe)')`
`parameters::model_parameters(fit)`

The code throws an error of: 
`Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match`

**Comment by bwiernik** [comment] 2021-08-24 16:25
What happens if you don't put your formula in quotes?

**Comment by IndrajeetPatil** [comment] 2021-08-24 18:57
I _think_ this is a duplicate of https://github.com/easystats/parameters/issues/523 and should be fixed in the development version on GitHub.

**Comment by strengejacke** [comment] 2021-08-25 06:26
yes, looks like it. Can you please try following installation steps to update your packages, and then try your example again?

```r
install.packages("insight", repos = "https://easystats.r-universe.dev")
install.packages("datawizard", repos = "https://easystats.r-universe.dev")
install.packages("parameters", repos = "https://easystats.r-universe.dev")
```

**Comment by jasonmoy28** [comment] 2021-09-01 04:34
Yes. The development version works. Any timeline on when to publish them on CRAN? I understand it's none of your problems. But my package depends on these packages, so would like to learn more about the timeline. Thanks!

**Closed** 2021-09-01 05:58 UTC
Labels: question :question:, waiting for response :love_letter:
