### ISSUE TITLE
Test for `{marginaleffects}` is failing

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#827] opened 2023-01-10 07:58 UTC
cc @vincentarelbundock 

ref: https://github.com/easystats/parameters/actions/runs/3880815160/jobs/6619203313

```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-marginaleffects.R:53'): multiple contrasts: Issue #779 ─────────
Error in ``[[<-.data.frame`(`*tmp*`, "type", value = c(expectation = "response"))`: replacement has 1 row, data has 0
Backtrace:
    ▆
 1. ├─base::suppressWarnings(...) at test-marginaleffects.R:53:2
 2. │ └─base::withCallingHandlers(...)
 3. └─marginaleffects::comparisons(...)
 4.   ├─base::`[[<-`(`*tmp*`, "type", value = `<chr>`) at marginaleffects/R/comparisons.R:422:4
 5.   └─base::`[[<-.data.frame`(`*tmp*`, "type", value = `<chr>`) at marginaleffects/R/comparisons.R:422:4
```

**Comment by strengejacke** [comment] 2023-01-10 13:05
Strange this happens only on one machine, though. Cannot reproduce locally.

**Comment by IndrajeetPatil** [comment] 2023-01-10 13:27
Yeah, the failure is seen on Ubuntu. 

@etiennebacher Can you please check if you can reproduce this failure with the devel-versions?

**Comment by vincentarelbundock** [comment] 2023-01-10 13:30
Frankly, I don't think we should bother. We can't replicate, it only affects a couple old versions, and this is a minor problem: the function returns NULL and NOT an incorrect result.

Feel free to just add a skip.

**Comment by IndrajeetPatil** [comment] 2023-01-10 14:04
The test is failing on R-devel. 

We can probably run the test only on Windows.

**Comment by etiennebacher** [comment] 2023-01-10 20:37
> @etiennebacher Can you please check if you can reproduce this failure with the devel-versions?

I won't have access to Ubuntu before the weekend

**Comment by vincentarelbundock** [comment] 2023-01-11 01:02
I just tried to look into this, but I no longer see a failure. Closing now, but feel free to re-open or comment again if I missed something.

Thanks!

**Closed by vincentarelbundock** 2023-01-11 01:02 UTC
