### ISSUE TITLE
`parameters.marginaleffects()`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#714] opened 2022-05-17 10:54 UTC
Following-up on an email exchange with @strengejacke:

By default, `marginaleffects` returns a data.frame with unit-level estimates of marginal effects. The `tidy()` method supplied by `marginaleffects` computes *Average Marginal Effects`. Most users are likely to want to look at those average marginal effects rather than the raw unit-level estimates.

Should the `parameters()` method call `tidy()` under the hood to return the average? That would probably be most intuitive to most users...

**Comment by strengejacke** [comment] 2022-05-17 10:56
> Should the parameters() method call tidy() under the hood to return the average? That would probably be most intuitive to most users...

I agree, in particular since you use a lot of data table, which is probably a good thing to do regarding the performance. Thus, I don't think it makes much sense "re-implementing" `tidy()`, but rather just call it from inside `model_parameters()`.

**Comment by strengejacke** [comment] 2022-05-17 10:57
duplicate of #665

**Comment by vincentarelbundock** [comment] 2022-05-17 11:01
Sorry for the duplicate. I'll look into this when I find a minute.

**Closed** 2022-06-18 00:21 UTC
Labels: enhancement :boom:
