### ISSUE TITLE
Group level parameters for Bayesian models: missing categorization

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#520] opened 2021-06-06 10:08 UTC
``` r
library(rstanarm)

model <- lme4::lmer(mpg ~ hp + (1 | carb), data = mtcars)
as.data.frame(parameters::model_parameters(model, effects = "random", group_level = TRUE))
#>     Parameter Level Coefficient        SE   CI    CI_low   CI_high Effects
#> 1 (Intercept)     1  0.40506064 0.8390523 0.95 -1.239452 2.0495729  random
#> 2 (Intercept)     2  0.11088289 0.7829275 0.95 -1.423627 1.6453925  random
#> 3 (Intercept)     3 -0.32486359 0.9369268 0.95 -2.161206 1.5114791  random
#> 4 (Intercept)     4 -0.77955416 0.7829275 0.95 -2.314064 0.7549555  random
#> 5 (Intercept)     6  0.09296535 1.0007322 0.95 -1.868434 2.0543645  random
#> 6 (Intercept)     8  0.49550886 1.0007322 0.95 -1.465890 2.4569080  random
#>   Group
#> 1  carb
#> 2  carb
#> 3  carb
#> 4  carb
#> 5  carb
#> 6  carb

model <- rstanarm::stan_lmer(mpg ~ hp + (1 | carb), data = mtcars, refresh = 0)
#> Warning: There were 2 divergent transitions after warmup. See
#> http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
#> to find out why this is a problem and how to eliminate them.
#> Warning: Examine the pairs() plot to diagnose sampling problems
as.data.frame(parameters::model_parameters(model, effects = "random", group_level = TRUE))
#>                             Parameter Effects      Median   CI        CI_low
#> 1                         (Intercept)   fixed 29.89964863 0.89  2.639477e+01
#> 2                                  hp   fixed -0.06474477 0.89 -8.377032e-02
#> 3               b[(Intercept) carb:1]  random  0.25531073 0.89 -1.615448e+00
#> 4               b[(Intercept) carb:2]  random  0.01858881 0.89 -2.008850e+00
#> 5               b[(Intercept) carb:3]  random -0.35885038 0.89 -3.160301e+00
#> 6               b[(Intercept) carb:4]  random -0.76024971 0.89 -3.363202e+00
#> 7               b[(Intercept) carb:6]  random  0.04998711 0.89 -2.328856e+00
#> 8               b[(Intercept) carb:8]  random  0.53060360 0.89 -1.430292e+00
#> 9 Sigma[carb:(Intercept),(Intercept)]  random  1.84533602 0.89  3.993646e-08
#>      CI_high      pd ROPE_Percentage     Rhat       ESS Prior_Distribution
#> 1 33.3100682 1.00000         0.00000 1.001716 1950.6053             normal
#> 2 -0.0456754 1.00000         1.00000 1.000241 3192.8600             normal
#> 3  2.7963006 0.63250         0.45325 1.002458 1668.8246               <NA>
#> 4  2.0196403 0.52150         0.51500 1.002701 1015.1630               <NA>
#> 5  1.2476072 0.66600         0.45875 1.002463  941.0397               <NA>
#> 6  0.8601550 0.80200         0.39200 1.002835  846.4382               <NA>
#> 7  2.7371017 0.54425         0.45450 1.002103 3050.9163               <NA>
#> 8  4.4246376 0.71775         0.41675 1.000822 1978.9531               <NA>
#> 9 11.1640447 1.00000         0.29150 1.003505  796.6928               <NA>
#>   Prior_Location Prior_Scale
#> 1       20.09062  15.0673701
#> 2        0.00000   0.2197599
#> 3             NA          NA
#> 4             NA          NA
#> 5             NA          NA
#> 6             NA          NA
#> 7             NA          NA
#> 8             NA          NA
#> 9             NA          NA
```

<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

For the stanreg model, the function returns also the fixed effects but, critically, is missing the `Group` and `Level` categorization, which makes it inconsistent with its frequentist counterpart and hard to analyze / postprocess

**Comment by strengejacke** [comment] 2022-04-06 16:47
duplicate of #685, no?

**Closed by strengejacke** 2022-04-06 16:47 UTC
Labels: consistency :green_apple: :apple:
