### ISSUE TITLE
`model_parameters` doesn't work with `clmm2`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#248] opened 2020-04-21 08:33 UTC
```r
# for reproducibility
set.seed(123)
library(ordinal)

# data
dat <- subset(soup, as.numeric(as.character(RESP)) <= 24)
dat$RESP <- dat$RESP[drop = TRUE]

# model
m1 <- 
  ordinal::clmm2(
  SURENESS ~ PROD,
  random = RESP,
  data = dat,
  link = "probit",
  Hess = TRUE,
  method = "ucminf",
  threshold = "symmetric"
)

summary(m1)
#> Cumulative Link Mixed Model fitted with the Laplace approximation
#> 
#> Call:
#> ordinal::clmm2(location = SURENESS ~ PROD, random = RESP, data = dat, 
#>     Hess = TRUE, link = "probit", threshold = "symmetric", method = "ucminf")
#> 
#> Random effects:
#>             Var   Std.Dev
#> RESP 0.05947608 0.2438772
#> 
#> Location coefficients:
#>          Estimate Std. Error z value Pr(>|z|)  
#> PRODTest  1.0900   0.1678     6.4953 8.2853e-11
#> 
#> No scale coefficients
#> 
#> Threshold coefficients:
#>           Estimate Std. Error z value
#> central    0.0310   0.1302     0.2380
#> spacing.1  0.2146   0.0392     5.4682
#> spacing.2  0.7451   0.0681    10.9440
#> 
#> log-likelihood: -283.6719 
#> AIC: 577.3439 
#> Condition number of Hessian: 239.9319

parameters::model_parameters(m1)
#> Error in formula.character(object, env = baseenv()): invalid formula "NULL": not a call
```

**Comment by strengejacke** [comment] 2020-04-21 08:36
``` r
set.seed(123)
library(ordinal)

# data
dat <- subset(soup, as.numeric(as.character(RESP)) <= 24)
dat$RESP <- dat$RESP[drop = TRUE]

# model
m1 <- 
  ordinal::clmm2(
    SURENESS ~ PROD,
    random = RESP,
    data = dat,
    link = "probit",
    Hess = TRUE,
    method = "ucminf",
    threshold = "symmetric"
  )

insight::get_parameters(m1)
#>   Parameter   Estimate   Component
#> 1   central 0.03098235 conditional
#> 2 spacing.1 0.21461394 conditional
#> 3 spacing.2 0.74509588 conditional
#> 4  PRODTest 1.09003580 conditional
parameters::model_parameters(m1)
#> Parameter   | Coefficient |   SE |        95% CI |     z |  df |      p
#> -----------------------------------------------------------------------
#> central     |        0.03 | 0.13 | [-0.22, 0.29] |  0.24 | 195 | 0.812 
#> spacing.1   |        0.21 | 0.04 | [ 0.14, 0.29] |  5.47 | 195 | < .001
#> spacing.2   |        0.75 | 0.07 | [ 0.61, 0.88] | 10.94 | 195 | < .001
#> PROD [Test] |        1.09 | 0.17 | [ 0.76, 1.42] |  6.50 | 195 | < .001
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-04-21 08:45
Hmm, not sure why this is not working for me. Here is the same `reprex` you posted above.
I also have all the updated versions of `easystats` packages.

``` r
set.seed(123)
library(ordinal)

# data
dat <- subset(soup, as.numeric(as.character(RESP)) <= 24)
dat$RESP <- dat$RESP[drop = TRUE]

# model
m1 <- 
  ordinal::clmm2(
    SURENESS ~ PROD,
    random = RESP,
    data = dat,
    link = "probit",
    Hess = TRUE,
    method = "ucminf",
    threshold = "symmetric"
  )

insight::get_parameters(m1)
#>   Parameter   Estimate   Component
#> 1   central 0.03098235 conditional
#> 2 spacing.1 0.21461394 conditional
#> 3 spacing.2 0.74509588 conditional
#> 4  PRODTest 1.09003580 conditional

parameters::model_parameters(m1)
#> Error in formula.character(object, env = baseenv()): invalid formula "NULL": not a call
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2020-02-28 r77874)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2020-04-21                                        
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                               
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                       
#>  backports     1.1.6      2020-04-05 [1] CRAN (R 4.0.0)                       
#>  bayestestR    0.6.0      2020-04-21 [1] Github (easystats/bayestestR@18abea8)
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.0)                       
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.0)                       
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.0)                       
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 4.0.0)                       
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                       
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                       
#>  fs            1.4.1      2020-04-04 [1] CRAN (R 4.0.0)                       
#>  glue          1.4.0      2020-04-03 [1] CRAN (R 4.0.0)                       
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                       
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 4.0.0)                       
#>  insight       0.8.3      2020-04-20 [1] CRAN (R 4.0.0)                       
#>  knitr         1.28       2020-02-06 [1] CRAN (R 4.0.0)                       
#>  lattice       0.20-40    2020-02-19 [2] CRAN (R 4.0.0)                       
#>  lifecycle     0.2.0.9000 2020-03-16 [1] Github (r-lib/lifecycle@355dcba)     
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.0)                       
#>  MASS          7.3-51.5   2019-12-20 [2] CRAN (R 4.0.0)                       
#>  Matrix        1.2-18     2019-11-27 [2] CRAN (R 4.0.0)                       
#>  numDeriv      2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.0)                       
#>  ordinal     * 2019.12-10 2019-12-15 [1] CRAN (R 4.0.0)                       
#>  parameters    0.6.1      2020-04-21 [1] Github (easystats/parameters@b70b584)
#>  pillar        1.4.3      2019-12-20 [1] CRAN (R 4.0.0)                       
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                       
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                       
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 4.0.0)                       
#>  reprex        0.3.0.9001 2020-03-25 [1] Github (tidyverse/reprex@a019cc4)    
#>  rlang         0.4.5      2020-03-01 [1] CRAN (R 4.0.0)                       
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 4.0.0)                       
#>  rstudioapi    0.11       2020-02-07 [1] CRAN (R 4.0.0)                       
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                       
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 4.0.0)                       
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                       
#>  styler        1.3.2.9000 2020-04-11 [1] Github (r-lib/styler@58f852d)        
#>  tibble        3.0.1      2020-04-20 [1] CRAN (R 4.0.0)                       
#>  ucminf        1.1-4      2016-08-18 [1] CRAN (R 4.0.0)                       
#>  vctrs         0.2.4      2020-03-10 [1] CRAN (R 4.0.0)                       
#>  withr         2.2.0      2020-04-20 [1] CRAN (R 4.0.0)                       
#>  xfun          0.13       2020-04-13 [1] CRAN (R 4.0.0)                       
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                       
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-devel/library
```

</details>


Here is the traceback I see:

```r
> traceback()
17: stop(gettextf("invalid formula %s: not a call", deparse2(x)), 
        domain = NA)
16: formula.character(object, env = baseenv())
15: formula(object, env = baseenv())
14: stats::as.formula(.safe_deparse(attr(x$scale, "terms", exact = TRUE)))
13: .compact_list(list(conditional = stats::as.formula(.safe_deparse(attr(x$location, 
        "terms", exact = TRUE))), scale = stats::as.formula(.safe_deparse(attr(x$scale, 
        "terms", exact = TRUE))), random = stats::as.formula(paste0("~", 
        parse(text = .safe_deparse(x$call))[[1]]$random))))
12: find_formula.clmm2(x)
11: find_formula(x)
10: find_random(x)
9: .make_family(x = x, fitfam = faminfo$family, logit.link = faminfo$link == 
       "logit", link.fun = faminfo$link, ...)
8: model_info.clm2(model, verbose = FALSE)
7: insight::model_info(model, verbose = FALSE)
6: .dof_method_ok(model, method)
5: degrees_of_freedom(model, method = "any")
4: .extract_parameters_generic(model, ci = ci, merge_by = merge_by, 
       standardize = standardize, effects = effects, robust = robust, 
       df_method = df_method, p_adjust = p_adjust, ...)
3: .model_parameters_generic(model = model, ci = ci, component = component, 
       bootstrap = bootstrap, iterations = iterations, merge_by = c("Parameter", 
           "Component"), standardize = standardize, exponentiate = exponentiate, 
       robust = FALSE, p_adjust = p_adjust, ...)
2: model_parameters.clmm2(m1)
1: parameters::model_parameters(m1)
```

**Comment by strengejacke** [comment] 2020-04-21 08:55
What does `insight::find_formula(m1)` return?

**Comment by IndrajeetPatil** [comment] 2020-04-21 08:59
```r
> insight::find_formula(m1)
Error in formula.character(object, env = baseenv()) : 
  invalid formula "NULL": not a call

> traceback()
7: stop(gettextf("invalid formula %s: not a call", deparse2(x)), 
       domain = NA)
6: formula.character(object, env = baseenv())
5: formula(object, env = baseenv())
4: stats::as.formula(.safe_deparse(attr(x$scale, "terms", exact = TRUE)))
3: .compact_list(list(conditional = stats::as.formula(.safe_deparse(attr(x$location, 
       "terms", exact = TRUE))), scale = stats::as.formula(.safe_deparse(attr(x$scale, 
       "terms", exact = TRUE))), random = stats::as.formula(paste0("~", 
       parse(text = .safe_deparse(x$call))[[1]]$random))))
2: find_formula.clmm2(m1)
1: insight::find_formula(m1)
```

**Comment by strengejacke** [comment] 2020-04-21 09:34
@mattansb @DominiqueMakowski Anyone who can reproduce this error?

**Comment by mattansb** [comment] 2020-04-21 09:46
Works for me...

**Comment by DominiqueMakowski** [comment] 2020-04-21 10:46
```
> # data
> dat <- subset(soup, as.numeric(as.character(RESP)) <= 24)
> dat$RESP <- dat$RESP[drop = TRUE]
> 
> # model
> m1 <- 
+     ordinal::clmm2(
+         SURENESS ~ PROD,
+         random = RESP,
+         data = dat,
+         link = "probit",
+         Hess = TRUE,
+         method = "ucminf",
+         threshold = "symmetric"
+     )
> insight::find_formula(m1)
$conditional
SURENESS ~ PROD
<environment: 0x000002e74240edf0>

$random
~RESP
<environment: 0x000002e74240edf0>
```
Works for me

**Comment by IndrajeetPatil** [comment] 2020-04-21 11:40
@strengejacke Can you please include session information in the reprex you posted, like I did?
I can then compare what's different on my computer compared to you. Thanks.

**Comment by strengejacke** [comment] 2020-04-21 11:45
``` r
set.seed(123)
library(ordinal)

# data
dat <- subset(soup, as.numeric(as.character(RESP)) <= 24)
dat$RESP <- dat$RESP[drop = TRUE]

# model
m1 <- 
  ordinal::clmm2(
    SURENESS ~ PROD,
    random = RESP,
    data = dat,
    link = "probit",
    Hess = TRUE,
    method = "ucminf",
    threshold = "symmetric"
  )

insight::get_parameters(m1)
#>   Parameter   Estimate   Component
#> 1   central 0.03098235 conditional
#> 2 spacing.1 0.21461394 conditional
#> 3 spacing.2 0.74509588 conditional
#> 4  PRODTest 1.09003580 conditional

parameters::model_parameters(m1)
#> Parameter   | Coefficient |   SE |        95% CI |     z |  df |      p
#> -----------------------------------------------------------------------
#> central     |        0.03 | 0.13 | [-0.22, 0.29] |  0.24 | 195 | 0.812 
#> spacing.1   |        0.21 | 0.04 | [ 0.14, 0.29] |  5.47 | 195 | < .001
#> spacing.2   |        0.75 | 0.07 | [ 0.61, 0.88] | 10.94 | 195 | < .001
#> PROD [Test] |        1.09 | 0.17 | [ 0.76, 1.42] |  6.50 | 195 | < .001
```

<details>

```
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-04-21                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)
#>  bayestestR    0.6.0      2020-04-20 [1] local         
#>  boot          1.3-24     2019-12-20 [1] CRAN (R 3.6.2)
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.2)
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.2)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.1)
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)
#>  glue          1.4.0      2020-04-03 [1] CRAN (R 3.6.3)
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.1)
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)
#>  insight       0.8.3      2020-04-21 [1] local         
#>  knitr         1.28       2020-02-06 [1] CRAN (R 3.6.2)
#>  lattice       0.20-41    2020-04-02 [1] CRAN (R 3.6.3)
#>  lme4          1.1-23     2020-04-07 [1] CRAN (R 3.6.3)
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)
#>  MASS          7.3-51.5   2019-12-20 [2] CRAN (R 3.6.3)
#>  Matrix        1.2-18     2019-11-27 [2] CRAN (R 3.6.3)
#>  minqa         1.2.4      2014-10-09 [1] CRAN (R 3.6.1)
#>  nlme          3.1-144    2020-02-06 [2] CRAN (R 3.6.3)
#>  nloptr        1.2.2.1    2020-03-11 [1] CRAN (R 3.6.3)
#>  numDeriv      2016.8-1.1 2019-06-06 [1] CRAN (R 3.6.0)
#>  ordinal     * 2019.12-10 2019-12-15 [1] CRAN (R 3.6.1)
#>  parameters    0.6.1      2020-04-20 [1] local         
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)
#>  rlang         0.4.5      2020-03-01 [1] CRAN (R 3.6.3)
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)
#>  statmod       1.4.34     2020-02-17 [1] CRAN (R 3.6.2)
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.1)
#>  ucminf        1.1-4      2016-08-18 [1] CRAN (R 3.6.0)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)
#>  xfun          0.13       2020-04-13 [1] CRAN (R 3.6.3)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)
#> 
#> [1] C:/Users/mail/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.3/library
```

</details>

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-04-21 11:56
Hmm, the main big difference I see is that I am using R-devel (`4.0.0`), while you are using the current version (`3.6.3`).

**Comment by strengejacke** [comment] 2020-04-21 12:48
So does `as.formula(NULL)` fail for you?

**Comment by IndrajeetPatil** [comment] 2020-04-21 14:01
Doch, es funktioniert:

```r
> as.formula(NULL)
list()
```

**Comment by IndrajeetPatil** [comment] 2020-04-25 19:38
With the example above, what does the following code give you? 

```r
> insight:::.safe_deparse(attr(m1$scale, "terms", exact = TRUE))
[1] "NULL"
```

**Comment by strengejacke** [comment] 2020-04-26 07:03
> With the example above, what does the following code give you?
> 
> ```r
> > insight:::.safe_deparse(attr(m1$scale, "terms", exact = TRUE))
> [1] "NULL"
> ```

Yes.

**Comment by strengejacke** [comment] 2020-04-26 07:04
Wait, just checked again, and I can reproduce your issue. I updated to R 4.0.0 and now I get the same error.

**Comment by strengejacke** [comment] 2020-04-26 07:12
closed in https://github.com/easystats/insight/commit/8ed88976f587a55334fbba42b7a46a8d97238be7

**Closed by strengejacke** 2020-04-26 07:12 UTC
Labels: invalid :x:
