### ISSUE TITLE
`model_parameters` struggles with `rma` objects inside function environment

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#176] opened 2019-12-24 19:19 UTC
I am trying to write a custom function that wraps around `model_parameters` but it seems to struggle with `rma` objects and I can't seem to figure out why. 

As you can see here, meta-analysis is successfully carried out inside the function environment, but then somehow `model_parameters` fails:

``` r
set.seed(123)

# dataframe
df <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
tryfn <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      measure = "GEN",
      intercept = TRUE,
      data = data,
      vtype = "LS",
      method = "REML",
      weighted = TRUE,
      test = "z",
      level = 95,
      digits = 4
    )
  
  # did this work?
  print(summary(mod))

  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}

# using the function
tryfn(df)
#> 
#> Random-Effects Model (k = 5; tau^2 estimator: REML)
#> 
#>   logLik  deviance       AIC       BIC      AICc 
#>  -2.5675    5.1349    9.1349    7.9075   21.1349   
#> 
#> tau^2 (estimated amount of total heterogeneity): 0.1935 (SE = 0.1438)
#> tau (square root of estimated tau^2 value):      0.4399
#> I^2 (total heterogeneity / total variability):   99.90%
#> H^2 (total variability / sampling variability):  1007.52
#> 
#> Test for Heterogeneity:
#> Q(df = 4) = 6082.5955, p-val < .0001
#> 
#> Model Results:
#> 
#> estimate      se    zval    pval   ci.lb   ci.ub 
#>   0.4377  0.2017  2.1697  0.0300  0.0423  0.8331  * 
#> 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#>
#> Error in as.data.frame.default(x[[i]], optional = TRUE): cannot coerce class '"function"' to a data.frame
```

<sup>Created on 2019-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2019-12-24                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                               
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                       
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                       
#>  bayestestR    0.4.0      2019-10-20 [1] CRAN (R 3.6.1)                       
#>  callr         3.4.0      2019-12-09 [1] CRAN (R 3.6.1)                       
#>  cli           2.0.0.9000 2019-12-23 [1] Github (r-lib/cli@0293ae7)           
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                       
#>  desc          1.2.0      2019-11-11 [1] Github (r-lib/desc@61205f6)          
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                       
#>  digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                       
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                       
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                       
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c)       
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                       
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                       
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                       
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                       
#>  insight       0.7.1.1    2019-12-24 [1] local                                
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.6.1)                       
#>  lattice       0.20-38    2018-11-04 [2] CRAN (R 3.6.1)                       
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                       
#>  Matrix        1.2-18     2019-11-27 [1] CRAN (R 3.6.1)                       
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                       
#>  metafor       2.1-0      2019-05-14 [1] CRAN (R 3.6.0)                       
#>  nlme          3.1-140    2019-05-12 [2] CRAN (R 3.6.1)                       
#>  parameters    0.3.0.1    2019-12-24 [1] Github (easystats/parameters@78e4442)
#>  pillar        1.4.3      2019-12-20 [1] CRAN (R 3.6.1)                       
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                       
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                       
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                       
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                       
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                       
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                       
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                       
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                       
#>  rlang         0.4.2      2019-11-23 [1] CRAN (R 3.6.1)                       
#>  rmarkdown     2.0        2019-12-12 [1] CRAN (R 3.6.1)                       
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                       
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                       
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                       
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                       
#>  testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.1)                       
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.1)                       
#>  usethis       1.5.1.9000 2019-12-12 [1] Github (r-lib/usethis@23dd62c)       
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                       
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.6.1)                       
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                       
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

Trace:

```r
 Error in eval(mf.yi, data, enclos = sys.frame(sys.parent())) : 
  object 'estimate' not found 
18.
eval(mf.yi, data, enclos = sys.frame(sys.parent())) 
17.
eval(mf.yi, data, enclos = sys.frame(sys.parent())) 
16.
metafor::rma(yi = estimate, sei = std.error, measure = "GEN", 
    intercept = TRUE, data = data, vtype = "LS", method = "REML", 
    weighted = TRUE, test = "z", level = i, digits = 4) 
15.
eval(call, parent.frame()) 
14.
eval(call, parent.frame()) 
13.
update.rma(x, level = i) 
12.
stats::update(x, level = i) 
11.
FUN(X[[i]], ...) 
10.
lapply(ci, function(i) {
    model <- stats::update(x, level = i)
    .data_frame(Parameter = params[[1]], CI = i * 100, CI_low = as.vector(model$ci.lb), 
        CI_high = as.vector(model$ci.ub)) ... 
9.
ci.rma(model, ci = ci, effects = effects, component = component, 
    method = robust) 
8.
ci(model, ci = ci, effects = effects, component = component, 
    method = robust) 
7.
withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage")) 
6.
suppressMessages(ci(model, ci = ci, effects = effects, component = component, 
    method = robust)) 
5.
.extract_parameters_generic(model, ci = ci, component = "conditional", 
    merge_by = merge_by, standardize = standardize, effects = effects, 
    robust = robust, ...) 
4.
.model_parameters_generic(model = model, ci = ci, bootstrap = bootstrap, 
    iterations = iterations, merge_by = "Parameter", standardize = standardize, 
    exponentiate = exponentiate, ...) 
3.
model_parameters.rma(mod) 
2.
parameters::model_parameters(mod) 
1.
tryfn(df) 

```

**Comment by strengejacke** [comment] 2019-12-26 12:47
The problem is `insight::get_data.rma()`, which tries to access the data from the environment, and searches for the data frame names `data`, although the data frame in the env is named `df`. Thus, it doesn't work.

**Comment by IndrajeetPatil** [comment] 2019-12-26 22:09
Is there no possible way to get this to work?
 
I want to use `model_parameters` in my package functions and so I will necessarily have to allow for the possibility that the users have named their data as something else than `data`.

**Comment by IndrajeetPatil** [comment] 2019-12-29 13:28
For example, this is the package context in which I plan to use this function 
https://github.com/IndrajeetPatil/ggstatsplot/blob/cfc0bd9ebb7def90713e86da7f03db9e21bb5cae/R/helpers_ggcoefstats_metaanalysis.R#L131

Since it doesn't work, I am currently just commenting it out and manually extracting parameters.

**Comment by strengejacke** [comment] 2019-12-29 17:58
can you put the data from the function call into the environment?

**Comment by IndrajeetPatil** [comment] 2019-12-29 18:32
Thanks, that worked!

One additional question: 
Do you think the `Parameter` row for the summary effect should be renamed? 

For a reference, I am showing below what the `broom` tidier returns for the same. I think something like `"summary effect"` or `"metaanalytic effect"` would be much more informative. What do you think?

``` r
set.seed(123)

# dataframe
df <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
tryfn <- function(data) {
  df <- data

  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      measure = "GEN",
      intercept = TRUE,
      data = df,
      vtype = "LS",
      method = "REML",
      weighted = TRUE,
      test = "z",
      level = 95,
      digits = 4
    )

  # exctracting model parameters in a dataframe
  list(
    "parameters" = tibble::as_tibble(parameters::model_parameters(mod)),
    "broom" = broom::tidy(mod, include_studies = TRUE, conf.int = TRUE)
  )
}

# using the function
tryfn(df)
#> $parameters
#> # A tibble: 6 x 8
#>   Parameter   Coefficient    SE CI_low CI_high      z            p    Weight
#>   <chr>             <dbl> <dbl>  <dbl>   <dbl>  <dbl>        <dbl>     <dbl>
#> 1 Study 1           0.111 0.05  0.0130  0.209    2.22 0.0264           400. 
#> 2 Study 2           0.245 0.111 0.0274  0.463    2.21 0.0273            81.2
#> 3 Study 3           0.8   0.001 0.798   0.802  800    0            1000000  
#> 4 Study 4           1.1   0.2   0.708   1.49     5.5  0.0000000380      25.0
#> 5 Study 5           0.03  0.01  0.0104  0.0496   3    0.00270        10000  
#> 6 (Intercept)       0.438 0.202 0.0423  0.833    2.17 0.0300            NA  
#> 
#> $broom
#> # A tibble: 6 x 8
#>   term    type    estimate std.error statistic p.value conf.low conf.high
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 1       study      0.111     0.05       2.22 NA        0.0130    0.209 
#> 2 2       study      0.245     0.111      2.21 NA        0.0274    0.463 
#> 3 3       study      0.8       0.001    800    NA        0.798     0.802 
#> 4 4       study      1.1       0.2        5.5  NA        0.708     1.49  
#> 5 5       study      0.03      0.01       3    NA        0.0104    0.0496
#> 6 overall summary    0.438     0.202      2.17  0.0300   0.0423    0.833
```

<sup>Created on 2019-12-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2019-12-29                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                               
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                       
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                       
#>  bayestestR    0.4.0      2019-10-20 [1] CRAN (R 3.6.1)                       
#>  broom         0.5.3.9000 2019-12-15 [1] local                                
#>  callr         3.4.0      2019-12-09 [1] CRAN (R 3.6.1)                       
#>  cli           2.0.0.9000 2019-12-23 [1] Github (r-lib/cli@0293ae7)           
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                       
#>  desc          1.2.0      2019-11-11 [1] Github (r-lib/desc@61205f6)          
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                       
#>  digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                       
#>  dplyr         0.8.3      2019-07-04 [1] CRAN (R 3.6.2)                       
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                       
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                       
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c)       
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                       
#>  generics      0.0.2      2019-03-05 [1] Github (r-lib/generics@c15ac43)      
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                       
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                       
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                       
#>  insight       0.7.1.1    2019-12-29 [1] local                                
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.6.1)                       
#>  lattice       0.20-38    2018-11-04 [2] CRAN (R 3.6.2)                       
#>  lifecycle     0.1.0      2019-08-01 [1] CRAN (R 3.6.1)                       
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                       
#>  Matrix        1.2-18     2019-11-27 [1] CRAN (R 3.6.1)                       
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                       
#>  metafor       2.1-0      2019-05-14 [1] CRAN (R 3.6.0)                       
#>  nlme          3.1-142    2019-11-07 [2] CRAN (R 3.6.2)                       
#>  parameters    0.3.0.1    2019-12-24 [1] Github (easystats/parameters@78e4442)
#>  pillar        1.4.3      2019-12-20 [1] CRAN (R 3.6.2)                       
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                       
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                       
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                       
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                       
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                       
#>  purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.1)                       
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                       
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                       
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                       
#>  rlang         0.4.2      2019-11-23 [1] CRAN (R 3.6.2)                       
#>  rmarkdown     2.0        2019-12-12 [1] CRAN (R 3.6.1)                       
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                       
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                       
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                       
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                       
#>  testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.1)                       
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.2)                       
#>  tidyr         1.0.0      2019-09-11 [1] CRAN (R 3.6.1)                       
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.6.2)                       
#>  usethis       1.5.1.9000 2019-12-12 [1] Github (r-lib/usethis@23dd62c)       
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                       
#>  vctrs         0.2.1      2019-12-17 [1] CRAN (R 3.6.2)                       
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                       
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.6.1)                       
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                       
#>  zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.5.1)                       
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.2/library
```

</details>

**Comment by IndrajeetPatil** [comment] 2020-01-25 13:33
Thanks. 

By the way, I actually didn't manage to get this to work for me. If I change the name of the data object to anything other than `df`, this doesn't work. So I am guessing there is no way to get this to work?

``` r
set.seed(123)

# dataframe
df1 <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
tryfn <- function(data) {
  df <- data
  
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = df
    )
  
  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}

# using the function
tryfn(df1)
#> Error in as.data.frame.default(x[[i]], optional = TRUE): cannot coerce class '"function"' to a data.frame
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2020-01-25                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.0)
#>  bayestestR    0.5.0   2020-01-18 [1] CRAN (R 3.6.0)
#>  callr         3.4.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  cli           2.0.1   2020-01-08 [1] CRAN (R 3.6.2)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.0)
#>  digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.0)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
#>  insight       0.8.0   2020-01-14 [1] CRAN (R 3.6.2)
#>  knitr         1.27    2020-01-16 [1] CRAN (R 3.6.0)
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.6.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  Matrix        1.2-18  2019-11-27 [2] CRAN (R 3.6.2)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  metafor       2.1-0   2019-05-14 [1] CRAN (R 3.6.0)
#>  nlme          3.1-142 2019-11-07 [2] CRAN (R 3.6.2)
#>  parameters    0.4.1   2020-01-17 [1] CRAN (R 3.6.0)
#>  pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.2)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
#>  rlang         0.4.3   2020-01-24 [1] CRAN (R 3.6.2)
#>  rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.5   2020-01-11 [1] CRAN (R 3.6.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.0)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.2)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] /Users/patil/Library/R/3.6/library
#> [2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by strengejacke** [comment] 2020-01-25 18:10
Maybe like this? `<<--`

``` r
library(tibble)
set.seed(123)

# dataframe
df1 <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
tryfn <- function(data) {
  mydat <<- data
  
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = mydat
    )
  
  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}

# using the function
tryfn(df1)
#> Parameter | Coefficient |   SE |       95% CI |      z |      p |      Weight
#> -----------------------------------------------------------------------------
#> Study 1   |        0.11 | 0.05 | [0.01, 0.21] |   2.22 | 0.026  |      400.00
#> Study 2   |        0.24 | 0.11 | [0.03, 0.46] |   2.21 | 0.027  |       81.16
#> Study 3   |        0.80 | 0.00 | [0.80, 0.80] | 800.00 | < .001 | 1.00000e+06
#> Study 4   |        1.10 | 0.20 | [0.71, 1.49] |   5.50 | < .001 |       25.00
#> Study 5   |        0.03 | 0.01 | [0.01, 0.05] |   3.00 | 0.003  |    10000.00
#> Overall   |        0.44 | 0.20 | [0.04, 0.83] |   2.17 | 0.030  |
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Closing, because not an parameters issue, I would say.

**Comment by IndrajeetPatil** [comment] 2020-01-25 18:33
Super-assignment? I will finally feel like a programmer ;)

**Comment by IndrajeetPatil** [comment] 2020-11-11 21:18
I am re-opening this because the proposed solution doesn't work for me in the package context. It leaves the following `NOTE` in `R CMD CHECK` and the discussion also mentions why it's not a good idea to use this operator in a package:
https://stackoverflow.com/questions/28312408/no-visible-binding-for-assignment

I guess the crux of the issue is:

Why this works **without super-assignment** in `broom`:

```r
set.seed(123)
# dataframe
df <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
foo_broom <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = data
    )
  
  # exctracting model parameters in a dataframe
  broom::tidy(mod)
}

# using the function
foo_broom(df)
#> # A tibble: 1 x 6
#>   term    type    estimate std.error statistic p.value
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>   <dbl>
#> 1 overall summary    0.438     0.202      2.17  0.0300
```

But not in `parameters`:

```r
# function to extract meta-analysis results
foo_parameters <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = data
    )
  
  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}

# using the function
foo_parameters(df)
#> Error in as.data.frame.default(x[[i]], optional = TRUE): cannot coerce class '"function"' to a data.frame
```

What are we doing differently in `parameters` that necessitates super-assignment?

**Comment by IndrajeetPatil** [comment] 2020-11-11 21:22
This is making my `broom` -> `easystats` transition in packages super-difficult. 

And, although I am probably the first one to rely on `easystats` packages in my own packages and to raise this issue, I won't be the last one, so I don't think the tag `invalid` is correct here. Others are bound to run into this issue and are going to get the same `NOTE` I did in their checks.

**Comment by strengejacke** [comment] 2020-11-11 21:45
broom does not include studies by default. However, when it does, it runs a separate meta analysis, that's probably different from the original meta analysis.

parameters, however, relies on the original metafor data frame, which is not directly accessible.

**Comment by strengejacke** [comment] 2020-11-11 21:45
See here: https://github.com/tidymodels/broom/blob/c0ae258b2648628e9e5b2058c27cbe4ffb70dec5/R/rma-tidiers.R#L75

**Comment by IndrajeetPatil** [comment] 2020-11-11 22:01
In that case, is it possible for `rma` method to gain a new argument like `include_studies`, which, when set to `FALSE` will completely by-pass `insight::get_data.rma()` and this issue can be avoided?
I actually just need the summary effect in my packages.

**Comment by strengejacke** [comment] 2020-11-11 22:08
I think it's actually not related to that, but rather to the computation of the CIs, which calls `update()`, and which then fails.

**Comment by strengejacke** [comment] 2020-11-11 22:09
``` r
set.seed(123)
# dataframe
df <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
foo_parameters <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = data
    )
  
  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}

# using the function
foo_parameters(df)
#> Parameter | Coefficient |       SE |      z |      p |       95% CI |   Weight
#> ------------------------------------------------------------------------------
#> Study 1   |        0.11 |     0.05 |   2.22 | 0.026  | [0.01, 0.21] |   400.00
#> Study 2   |        0.24 |     0.11 |   2.21 | 0.027  | [0.03, 0.46] |    81.16
#> Study 3   |        0.80 | 1.00e-03 | 800.00 | < .001 | [0.80, 0.80] | 1.00e+06
#> Study 4   |        1.10 |     0.20 |   5.50 | < .001 | [0.71, 1.49] |    25.00
#> Study 5   |        0.03 |     0.01 |   3.00 | 0.003  | [0.01, 0.05] | 10000.00
#> Overall   |        0.44 |     0.20 |   2.17 | 0.030  |              |
```

<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed** 2020-11-11 22:08 UTC
Labels: invalid :x:, question :question:

**Comment by IndrajeetPatil** [comment] 2020-11-11 22:26
I also need the CIs though. 😭

So the problem with the `broom` approach is that it's running the meta-analysis twice? The estimates and the CIs don't change depending on whether studies are included in the output or not, so is the concern more about computational efficiency? 

Basically I am wondering why we don't do the same thing as `broom` does. I am guessing there are some advantages to the `parameters` approach?

**Comment by strengejacke** [comment] 2020-11-11 23:12
I haven't looked at the broom code before, that's why the implementations differ. Maybe I can use summary() to get the CI, maybe that works.

**Comment by strengejacke** [comment] 2020-11-12 07:40
should work now.

**Comment by strengejacke** [comment] 2020-11-12 07:41
``` r
set.seed(123)
# dataframe
df <-
  tibble::tribble(
    ~estimate, ~std.error,
    0.111, 0.05,
    0.245, 0.111,
    0.8, 0.001,
    1.1, 0.2,
    0.03, 0.01
  )

# function to extract meta-analysis results
foo_parameters <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = data
    )
  
  # exctracting model parameters in a dataframe
  parameters::model_parameters(mod)
}


# function to extract meta-analysis results
foo_broom <- function(data) {
  # model
  mod <-
    metafor::rma(
      yi = estimate,
      sei = std.error,
      data = data
    )
  
  # exctracting model parameters in a dataframe
  broom::tidy(mod, conf.int = TRUE, include_studies = TRUE)
}

# using the function
foo_parameters(df)
#> Parameter | Coefficient |       SE |       95% CI |      z |      p |   Weight
#> ------------------------------------------------------------------------------
#> Study 1   |        0.11 |     0.05 | [0.01, 0.21] |   2.22 | 0.026  |   400.00
#> Study 2   |        0.24 |     0.11 | [0.03, 0.46] |   2.21 | 0.027  |    81.16
#> Study 3   |        0.80 | 1.00e-03 | [0.80, 0.80] | 800.00 | < .001 | 1.00e+06
#> Study 4   |        1.10 |     0.20 | [0.71, 1.49] |   5.50 | < .001 |    25.00
#> Study 5   |        0.03 |     0.01 | [0.01, 0.05] |   3.00 | 0.003  | 10000.00
#> Overall   |        0.44 |     0.20 | [0.04, 0.83] |   2.17 | 0.030  |

# using the function
foo_broom(df)
#> # A tibble: 6 x 8
#>   term    type    estimate std.error statistic p.value conf.low conf.high
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 1       study      0.111     0.05       2.22 NA        0.0130    0.209 
#> 2 2       study      0.245     0.111      2.21 NA        0.0274    0.463 
#> 3 3       study      0.8       0.001    800    NA        0.798     0.802 
#> 4 4       study      1.1       0.2        5.5  NA        0.708     1.49  
#> 5 5       study      0.03      0.01       3    NA        0.0104    0.0496
#> 6 overall summary    0.438     0.202      2.17  0.0300   0.0423    0.833
```

<sup>Created on 2020-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-11-12 07:45
You are the best, Daniel! Thanks a lot :)

**Comment by IndrajeetPatil** [comment] 2020-11-24 11:56
One last thing on this:
Is there something in `model_parameters.rma`, similar to `include_studies` argument for `broom::tidy.rma`?
As a user, it would be nice to have the ability to retain or drop the study estimates.
