### ISSUE TITLE
model_parameters for FA and PCA threshold argument broken

### ISSUE THREAD

**Issue by profandyfield** [easystats/parameters#477] opened 2021-04-21 14:21 UTC
`model_paramaters()` for factor analysis and PCA models from psych is behaving weirdly when threshold is used (assuming it's not user error). Basically, certain values of threshold return the error `Can't export table to text, data frame is empty.`

Minimal example:

```
raq_fa <- readr::read_csv("https://www.discovr.rocks/csv/raq.csv") %>% 
  dplyr::select(-id) %>% 
  psych::fa(nfactors = 4)
parameters::model_parameters(raq_fa, threshold = 0.2, sort = TRUE)
```

returns error 'Can't export table to text, data frame is empty.' However

Omit `threshold` argument works:

```
parameters::model_parameters(raq_fa, sort = TRUE)
```

Lower threshold works:

```
parameters::model_parameters(raq_fa, threshold = 0.1, sort = TRUE)
```

Any idea what's going on here?

**Comment by bwiernik** [comment] 2021-04-21 14:36
Duplicate of https://github.com/easystats/parameters/issues/474

Already fixed if you install the master branch of *insight* from github

**Closed by bwiernik** 2021-04-21 14:36 UTC

**Comment by IndrajeetPatil** [comment] 2021-04-21 14:46
Reprex showing that this has been fixed in the development version:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

raq_fa <- readr::read_csv("https://www.discovr.rocks/csv/raq.csv") %>% 
  dplyr::select(-id) %>% 
  psych::fa(nfactors = 4)
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   id = col_character()
#> )
#> ℹ Use `spec()` for the full column specifications.
#> Loading required namespace: GPArotation

parameters::model_parameters(raq_fa, threshold = 0.2, sort = TRUE)
#> # Rotated loadings from Factor Analysis (oblimin-rotation)
#> 
#> Variable |  MR1  | MR4  | MR3  | MR2  | Complexity | Uniqueness
#> ---------------------------------------------------------------
#> raq_21   | 0.61  |      |      |      |    1.05    |    0.53   
#> raq_04   | 0.53  |      |      |      |    1.24    |    0.58   
#> raq_16   | 0.51  |      |      |      |    1.26    |    0.54   
#> raq_01   | 0.51  |      |      |      |    1.31    |    0.63   
#> raq_12   | 0.50  |      | 0.24 |      |    1.48    |    0.55   
#> raq_20   | 0.48  |      |      |      |    1.48    |    0.73   
#> raq_05   | 0.43  |      |      |      |    1.25    |    0.70   
#> raq_03   | -0.43 |      |      | 0.36 |    2.06    |    0.53   
#> raq_08   |       | 0.85 |      |      |    1.02    |    0.35   
#> raq_11   |       | 0.75 |      |      |    1.06    |    0.37   
#> raq_17   |       | 0.67 |      |      |    1.07    |    0.42   
#> raq_06   |       |      | 0.81 |      |    1.04    |    0.40   
#> raq_18   | 0.29  |      | 0.53 |      |    1.57    |    0.46   
#> raq_13   |       |      | 0.48 |      |    1.43    |    0.53   
#> raq_07   | 0.29  |      | 0.47 |      |    1.70    |    0.51   
#> raq_14   | 0.33  |      | 0.38 |      |    2.01    |    0.58   
#> raq_10   |       |      | 0.35 |      |    1.22    |    0.80   
#> raq_15   |       |      | 0.27 |      |    3.08    |    0.68   
#> raq_09   |       |      |      | 0.59 |    1.03    |    0.66   
#> raq_02   |       |      |      | 0.48 |    1.15    |    0.74   
#> raq_22   |       |      |      | 0.48 |    1.40    |    0.75   
#> raq_19   |       |      |      | 0.36 |    1.56    |    0.76   
#> raq_23   |       |      |      | 0.35 |    1.71    |    0.88   
#> 
#> The 4 latent factors (oblimin rotation) accounted for 40.48% of the total variance of the original data (MR1 = 13.74%, MR4 = 9.95%, MR3 = 10.31%, MR2 = 6.48%).
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
